<?php
include "db.php" ?>

<?php
$conn->query("SET NAMES utf8");
?>
<!DOCTYPE html>
<html class="page page_auth_yes">
    <head>
        <title>Eco Quest</title>
        <meta charset="utf-8">
        <meta name="description" content="Сервис улучшающий мир">
        <link rel="stylesheet" type="text/css" href="css/main.css">

        <script id="jqueryScript" type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="plugins/slider/js/jquery.flexslider-min.js"></script>
        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery('.flexslider').flexslider({
                    animation: 'fade',
                    controlNav: false,
                    directionNav: false
                });
            });
        </script>
    </head>

    <body class="page__body">
        <header class="header">
            <div class="container">
                <div class="header__col">
                    <nav class="main-menu">
                        <a class="link" href="events.phtml">События</a>
                        <a class="link" href="news.html">Новости</a>
                    </nav>
                </div>

                <div class="header__col">
                    <a class="logo link" href="index.phtml"><i class="fa fa-leaf"></i>Eco Quest</a>
                </div>

                <div class="header__col">
                    <nav class="authorization-menu">
                        <a class="link" href="registration.html">Регистрация</a>
                        <a class="link" href="profile.phtml">Вход</a>
                    </nav>
                </div>
            </div>
        </header>

        <section class="content content_type_main">
            <div class="container">
                <div class="gallery">
                    <div class="location">
                        <h1 class="location__title">Ваша<span class="label">локация</span></h1>
                        <p class="location__description">
                            Для того чтобы максимально точечно предлагать вам квесты,
                            нам нужно знать ваше местоположение.
                        </p>

                        <select class="select">
                            <option class="select__option" value="1">Страна</option>
                            <option class="select__option" value="2">Украина</option>
                            <option class="select__option" value="3">Россия</option>
                        </select>

                        <select class="select">
                            <option class="select__option" value="0">Город</option>
                            <option class="select__option" value="1">Казань</option>
                            <option class="select__option" value="2">Иннополис</option>
                            <option class="select__option" value="3">Москва</option>
                        </select>

                        <div class="location__wrap">
                            <a class="btn" href="#">Сохранить</a>
                        </div>
                    </div>

                    <div class="flex-container">
                        <div class="flexslider">
                            <ul class="slides">
                                <li><a href="#"><img src="images/index-1.jpg" /></a></li>
                                <li><img src="images/index-2.jpg" /></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <section class="section">
                    <div class="widget-area">

<?php
$sql = "SELECT * FROM events WHERE events.finished = false LIMIT 3";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $eid = $row["Id"];
        $sql = "SELECT COUNT(*) as total FROM event_participants WHERE Event_id = " . $row["Id"];
        $cnt_res = $conn->query($sql);
        $data = $cnt_res->fetch_assoc();
        $cnt = $data["total"];
        $date = $row["Date_start"];
        $date = strtotime($date);
        $day = date("d", $date);
        $mon = date("M", $date);
        $year = date("Y", $date);

        echo ("<div class=\"widget\">
                            <div class=\"widget__body\">
                                <div class=\"goal goal_align_center\">
                                    <p class=\"goal__subtitle\">".$row["Type"]."</p>
                                    <h2 class=\"goal__title\">".$row["Title"]."</h2>
                                    <div class=\"goal__body\">
                                        <img class=\"photo\" src=\"".$row["Image_link"]."\">
                                        <p class=\"text\">
                                            ".$row["Description"]."
                                        </p>
                                    </div>

                                    <ul class=\"metrics\">
                                        <li class=\"metrics__item\"><i class=\"fa fa-users\"></i>".$cnt."</li>
                                        <li class=\"metrics__item\"><i class=\"fa fa-clock-o\"></i>".$day." " .$mon. " " .$year."</li>
                                    </ul>

                                    <div class=\"clear\"></div>
                                </div>
                            </div>
                            <div class=\"widget__foot\">
                                <a class=\"btn\" href=\"event.phtml?eventId=".$row["Id"]."\">Присоединиться</a>
                                <div class=\"counter counter_state_normal\">
                                    <span class=\"counter__wrap\">
                                        <span class=\"counter__result\">".$row["points"]."</span>
                                    </span>
                                </div>
                            </div>
                        </div>");
    }}
?>
                        <div class="clear"></div>
                    </div>
                </section>
            </div>
        </section>

        <footer class="footer">
            <div class="container">
                <div class="footer-menu">
                    <div class="column">
                        <ul class="footer-menu__list">
                            <li class="footer-menu__item">
                                <a class="link" href="about.html">О проекте</a>
                            </li>
                            <li class="footer-menu__item">
                                <a class="link" href="team.html">Разработчики</a>
                            </li>
                            <li class="footer-menu__item">
                                <a class="link" href="rules.html">Правила</a>
                            </li>
                            <li class="footer-menu__item">
                                <a class="link" href="mailto:e.musatova@innopolis.ru,v.milenko@innopolis.ru">Контакты</a>
                            </li>
                        </ul>
                    </div>

                    <div class="column">
                        <div class="copyright">© 2016 Eco Quest<br>Сервис улучшающий мир</div>
                    </div>

                    <div class="column">
                        <div class="social-block">
                            <span class="social-block__title">Соцсети</span>
                            <div class="social-block__wrap">
                                <a class="link" href="vk.html"><i class="fa fa-vk"></i></a>
                                <a class="link" href="fb.html"><i class="fa fa-facebook"></i></a>
                                <a class="link" href="tw.html"><i class="fa fa-twitter"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>