<?php
include "db.php" ?>

<?php
error_reporting(0);
$conn->query("SET NAMES utf8");
try{
    $requested = $_GET["userId"];

}
catch (Exception $e){

}
if($requested == null) {
    $sql = "SELECT * FROM users,levels where `name`='AsTex' and levels.level=users.Level";
}
else{
    $sql = "SELECT * FROM users,levels where `id`=".$requested." and levels.level=users.Level";
}
$result = $conn->query($sql);
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $uid = $row["id"];
        $name = $row["Name"];
        $experience = $row["Experience"];
        $level = $row["Level"];
        $image = $row["Picture_link"];
        $level_description = $row["description"];
        $level_class = $row["css_class"];
    }
}

?>
<!DOCTYPE html>
<html class="page page_auth_yes">
<head>
    <title>Eco Quest</title>
    <meta charset="utf-8">
    <meta name="description" content="Сервис, помогающий достигать поставленных целей">
    <link rel="stylesheet" type="text/css" href="css/main.css">
    <script src="js/moment.min.js"></script>
</head>

<body class="page__body">
<header class="header">
    <div class="container">
        <div class="header__col">
            <nav class="main-menu">
                <a class="link" href="events.html">События</a>
                <a class="link" href="news.html">Новости</a>
            </nav>
        </div>

        <div class="header__col">
            <a class="logo link" href="index.html">Eco Quest</a>
        </div>

        <div class="header__col">
            <nav class="authorization-menu">
                <a class="link" href="registration.html">Регистрация</a>
                <a class="link" href="login.html">Вход</a>
            </nav>
        </div>
    </div>
</header>

<section class="content content_type_user">
    <div class="container">
        <aside class="panel">
            <div class="user">
                <header class="user__header">
                    <div class="user__exp">
                        <span class="value"><?php echo($experience) ?></span>
                        <span class="param">опыт</span>
                    </div>

                    <div class="user__photo">
                        <img class="photo" src="<?php echo($image) ?>">
                    </div>

                    <div class="user__level">
                        <span class="value"><?php echo($level) ?></span>
                        <span class="param">уровень</span>
                    </div>

                    <h3 class="user__name"><?php echo($name) ?></h3>
                </header>

                <footer class="user__footer">
                    <div class="user__progress">
                        <p class="user__role <?php echo($level_class) ?>"><?php echo($level_description) ?></p>
                        <p class="user__info"><span class="value"> <?php echo(100 - $experience) ?></span> до следующего
                            уровня</p>
                    </div>

                    <ul class="user-menu">
                        <li class="user-menu__item">
                            <a class="link" href="events.html"><i class="fa fa-calendar"></i>События</a>
                        </li>
                        <li class="user-menu__item">
                            <a class="link" href="friends.html"><i class="fa fa-users"></i>Друзья</a>
                        </li>
                        <li class="user-menu__item">
                            <a class="link" href="settings.html"><i class="fa fa-dashboard"></i>Настройки</a>
                        </li>
                        <li class="user-menu__item">
                            <a class="link" href="logout.html"><i class="fa fa-sign-out"></i>Выход</a>
                        </li>
                    </ul>
                </footer>
            </div>
            <?php
            $result = $conn->query("SELECT * FROM user_achievements JOIN achievements ON achievements.Id = achievement_id WHERE user_id=" . $uid . " and achievements.Id = achievement_id");
            if ($result->num_rows > 0) {
                echo("<div class=\"frame-widget achievements\">");
                while ($row = $result->fetch_assoc()) {
                    echo("<section class=\"achievement\">");
                    echo("<i class=\"achievement__icon " . $row["css_class"] . "\"></i>");
                    echo("<h3 class=\"achievement__title\">" . $row["Title"] . "</h3>");
                    echo("<div class=\"achievement__date\">" . date("d M Y", strtotime($row["Date_received"])) . "</div>");
                    echo("</section>");
                }
                echo("</div>");
            }
            ?>
        </aside>
        <section class="section">
            <div class="widget-area">
                <div class="widget-area__col widget-area__col_position_left">
                    <h4 class="widget-area__subtitle widget-area__subtitle_type_term">Активные</h4>
                    <?php
                    $sql = "SELECT * FROM events,event_participants WHERE event_participants.User_id = " . $uid . " and events.finished = false and events.Id=event_participants.Event_id";
                    $result = $conn->query($sql);
                    if ($result->num_rows > 0) {
                        while ($row = $result->fetch_assoc()) {
                            $eid=$row["Id"];
                            $sql = "SELECT COUNT(*) as total FROM event_participants WHERE Event_id = " . $row["Id"];
                            $cnt_res = $conn->query($sql);
                            $data = $cnt_res->fetch_assoc();
                            $cnt = $data["total"];
                            $date = $row["Date_start"];
                            $date = strtotime($date);
                            $day = date("d", $date);
                            $mon = date("M", $date);
                            $year = date("Y", $date);
                            echo("<div class=\"widget\">");
                            echo("<div class=\"widget__body\">");
                            echo("<div class=\"goal\">");
                            echo("<p class=\"goal__subtitle\">" . $row["Type"] . "</p>");
                            echo("<h2 class=\"goal__title\"><a class=\"link\" href=\"event.phtml?eventId=".$eid."\">" . $row["Title"] . "</a></h2>");
                            echo("<ul class=\"metrics\">");
                            echo("<li class=\"metrics__item\"><i class=\"fa fa-users\"></i>" . $cnt . "</li>");
                            echo("<li class=\"metrics__item\"><i class=\"fa fa-clock-o\"></i>" . $day . " " . $mon . " " . $year . "</li>");
                            echo("</ul>");
                            echo("<div class=\"counter counter_state_normal\">");
                            echo("<span class=\"counter__wrap\">");
                            echo("<span class=\"counter__result\">" . $row["points"]*($row["progress"]/100) . "</span>");
                            echo("</span>");
                            echo("</div>");
                            echo("<div class=\"clear\"></div>");
                            echo("</div>");
                            echo("</div>");
                            echo("<div class=\"widget__foot\">");
                            echo("<div class=\"progressbar\">");
                            echo("<div class=\"progressbar__wrap\">");
                            echo("<div class=\"progressbar__end\" style=\"width: " . (100-$row["progress"]) . "%;\"></div>");
                            echo("</div>");
                            echo("</div>");
                            echo("</div>");
                            echo("</div>");
                        }
                    }
                    ?>

                </div>

                <div class="widget-area__col widget-area__col_position_right">
                    <h4 class="widget-area__subtitle">Завершённые</h4>
                    <?php
                    $sql = "SELECT * FROM events,event_participants WHERE event_participants.User_id = " . $uid . " and events.finished = true and events.Id=event_participants.Event_id";
                    $result = $conn->query($sql);
                    if ($result->num_rows > 0) {
                        while ($row = $result->fetch_assoc()) {
                            $eid = $row["Id"];
                            $sql = "SELECT COUNT(*) as total FROM event_participants WHERE Event_id = " . $row["Id"];
                            $cnt_res = $conn->query($sql);
                            $data = $cnt_res->fetch_assoc();
                            $cnt = $data["total"];
                            $failed = $row["failed"];
                            if ($failed) {
                                $res = "Провалено";
                            } else {
                                $res = "Завершено";
                            }
                            $date = $row["Date_start"];
                            $date = strtotime($date);
                            $day = date("d", $date);
                            $mon = date("F", $date);
                            $year = date("Y", $date);

                            $date_e = $row["Date_end"];
                            $date_e = strtotime($date_e);
                            $day_e = date("d", $date_e);
                            $mon_e = date("F", $date_e);
                            $year_e = date("Y", $date_e);
                            if ($failed) {

                                echo("<div class=\"widget widget_status_failed\">");
                            } else {
                                echo("<div class=\"widget\">");
                            }
                            echo("<div class=\"widget__body\">");
                            echo("<div class=\"goal\">");
                            echo("<p class=\"goal__subtitle\">" . $row["Type"] . "</p>");
                            echo("<h2 class=\"goal__title\"><a class=\"link\" href=\"event.phtml?eventId=".$eid."\">" . $row["Title"] . "</a></h2>");
                            echo("<ul class=\"metrics\">");
                            echo("<li class=\"metrics__item\"><i class=\"fa fa-users\"></i>" . $cnt . "</li>");
                            echo("<li class=\"metrics__item\"><i class=\"fa fa-clock-o\"></i>" . $day . " " . $mon . " " . $year . "</li>");
                            echo("</ul>");
                            if ($failed) {
                                echo("<div class=\"counter counter_state_minus\">");
                            } else {
                                echo("<div class=\"counter counter_state_plus\">");
                            }

                            echo("<span class=\"counter__wrap\">");
                            echo("<span class=\"counter__result\">" . $row["points"]*($row["progress"]/100) . "</span>");
                            echo("</span>");
                            echo("</div>");
                            echo("<div class=\"clear\"></div>");
                            echo("</div>");
                            echo("</div>");
                            echo("<div class=\"widget__foot\">");

                            echo("<p class=\"goal-status\">" . $res . "<span class=\"goal-date\">" . $day_e . " " . $mon_e . " " . $year_e . "</span></p>");
                            echo("</div>");
                            echo("</div>");
                        }
                    }
                    ?>
                </div>

                <div class="clear"></div>
            </div>

            <div class="widget-area">
                <h4 class="widget-area__subtitle widget-area__subtitle_type_term">
                    Ближайшие события<span class="goal-date">&nbsp;&nbsp;(до начала менее 5 дней)</span>
                </h4>

                <div class="widget-area__col widget-area__col_position_left">
                    <?php
                    $today = getdate();
                    $today = new DateTime(date('Y-m-d', time()));
                    $coming = $today->add(new DateInterval("P5D"));
                    $today = new DateTime(date('Y-m-d', time()));
                    $sql = "SELECT * FROM events WHERE Date_start <= '" . $coming->format('Y-m-d') . "' AND Date_start > '" . $today->format('Y-m-d') . "' ORDER BY Date_start ASC";
                    $result = $conn->query($sql);
                    if ($result->num_rows > 0) {
                        while ($row = $result->fetch_assoc()) {
                            $sql = "SELECT COUNT(*) as total FROM event_participants WHERE Event_id = " . $row["Id"];
                            $cnt_res = $conn->query($sql);
                            $data = $cnt_res->fetch_assoc();
                            $date = $row["Date_start"];
                            $date = strtotime($date);
                            $day = date("d", $date);
                            $mon = date("M", $date);
                            echo("<div class=\"widget\">");
                            echo("<div class=\"widget__body\">");
                            echo("<div class=\"task\">");
                            echo("<a class=\"deadline\" rel=\"tooltip\" data-placement=\"top\" data-original-title=\"Дедлайн\">");
                            echo("<span class=\"deadline__day\">" . $day . "</span>");
                            echo("<br>");
                            echo("<span class=\"deadline__month\">".$mon."</span>");
                            echo("</a>");
                            echo("<div class=\"task__wrap\">");
                            echo("<h3 class=\"task__title\"><a class=\"link\" href=\"event.html\">" . $row["Title"] . "</a></h3>");
                            echo("<p class=\"task__description\">" . $row["Short_Description"] . "</p>");
                            echo("</div>");
                            echo("</div>");
                            echo("</div>");
                            echo("</div>");
                        }
                    }
                    ?>
                </div>


                <div class="clear"></div>
            </div>
        </section>
    </div>
</section>

<footer class="footer">
    <div class="container">
        <div class="footer-menu">
            <div class="column">
                <ul class="footer-menu__list">
                    <li class="footer-menu__item">
                        <a class="link" href="about.html">О проекте</a>
                    </li>
                    <li class="footer-menu__item">
                        <a class="link" href="team.html">Разработчики</a>
                    </li>
                    <li class="footer-menu__item">
                        <a class="link" href="rules.html">Правила</a>
                    </li>
                    <li class="footer-menu__item">
                        <a class="link" href="mailto:e.musatova@innopolis.ru,v.milenko@innopolis.ru">Контакты</a>
                    </li>
                </ul>
            </div>

            <div class="column">
                <div class="copyright">© 2016 Eco Quest<br>Сервис улучшающий мир</div>
            </div>

            <div class="column">
                <div class="social-block">
                    <span class="social-block__title">Соцсети</span>
                    <div class="social-block__wrap">
                        <a class="link" href="vk.html"><i class="fa fa-vk"></i></a>
                        <a class="link" href="fb.html"><i class="fa fa-facebook"></i></a>
                        <a class="link" href="tw.html"><i class="fa fa-twitter"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>